language: python

python: 
  - "3.6"

install: 
 - pip --version
 - pip install requirements.txt #dependencies need to be here. in the requirements.txt 

 script: pytest

# blocklist
branches:
  except:
    - developer #What branches not to build 

# safelist
branches: 
  only:
  - master


  #What we have found, is that when testing the software, we test the unit testing no the script itself
  #This means that we need to make test for the different challenges. We can use either pytest or a different one. 
  #We need to make sure we understand this and how to do it correctly. more unit testing :D